pipelines:
  publish:
    blubberfile: blubber.yaml
    stages:
      - name: dev
        build: dev
        publish:
          image:
            tags: [dev]
  wmf-publish:
      - name: build
        build:
          variant: production
          excludes:
            - .git
            - node_modules
      - name: publish
        publish:
          image:
            id: "${build.imageID}"
            tags: [ "${setup.branch}" ]
